name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g web-ext
        
    - name: Validate extension
      run: |
        web-ext lint
        
    - name: Build extension
      run: |
        web-ext build --overwrite-dest
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: snapix-extension
        path: web-ext-artifacts/ 